WorkWithCSV.WebApp/Models/ErrorViewModel.cs
using System;

namespace WorkWithCSV.WebApp.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

WorkWithCSV.WebApp/Models/Home/HomeModel.cs
using System.Collections.Generic;
using WorkWithCSV.Domain;

namespace WorkWithCSV.WebApp.Models.Home
{
    public class HomeModel
    {
        public List<Category> Categories { get; set; }
    }
}

WorkWithCSV.WebApp/Models/Tree/TreeModel.cs
using System.Collections.Generic;
using WorkWithCSV.Domain;

namespace WorkWithCSV.WebApp.Models.Tree
{
    public class SeededCategories
    {
        public int? Seed { get; set; }
        public List<Category> Categories { get; set; }
    }
}

WorkWithCSV.WebApp/Controllers/HomeController.cs
using System.Diagnostics;
using Microsoft.AspNetCore.Mvc;
using WorkWithCSV.Services.Interfaces;
using WorkWithCSV.WebApp.Models;

using WorkWithCSV.WebApp.Models.Home;
using WorkWithCSV.WebApp.Models.Tree;

namespace WorkWithCSV.WebApp.Controllers
{
    public class HomeController : Controller
    {
        private readonly ICategoryService _categoryService;

        public HomeController(ICategoryService categoryService)
        {
            _categoryService = categoryService;
        }

        public IActionResult Index()
        {
            var categories = _categoryService.GetAllCategorys();

            var model = new HomeModel
            {
                Categories = categories
            };

            return View(model);
        }

        [HttpPost]
        public IActionResult Remove(int id)
        {
            _categoryService.Remove(id);
            return RedirectToAction("About");
        }

        public IActionResult About()
        {
            var categories = _categoryService.GetAllCategorys();
            var model = new SeededCategories
            {
                Seed = null,
                Categories = categories
            };
            return View(model);
        }

        public ActionResult _TreeCategories()
        {
            var categories = _categoryService.GetAllCategorys();
            var model = new SeededCategories
            {
                Seed = null,
                Categories = categories
            };
            return PartialView(model);
        }

        public IActionResult Contact()
        {
            ViewData["Message"] = "Your contact page.";

            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

WorkWithCSV.WebApp/Controllers/TreeController.cs
using Microsoft.AspNetCore.Mvc;
using System.Linq;
using WorkWithCSV.Services.Interfaces;
using WorkWithCSV.WebApp.Models.Tree;

namespace WorkWithCSV.WebApp.Controllers
{
    public class TreeController : Controller
    {
        private readonly ICategoryService _categoryService;

        public TreeController(ICategoryService categoryService)
        {
            _categoryService = categoryService;
        }

        public IActionResult Index()
        {
            var categories = _categoryService.GetAllCategorys();
            var model = new SeededCategories
            {
                Seed = null,
                Categories = categories
            };
            return View(model);
        }

        [HttpPost]
        public IActionResult Remove(int id)
        {
            _categoryService.Remove(id);
            return RedirectToAction("Index");
        }

        public ActionResult _TreeCategories()
        {
            var categories = _categoryService.GetAllCategorys();
            var model = new SeededCategories
            {
                Seed = null,
                Categories = categories
            };
            return PartialView(model);
        }

        //public ActionResult Edit(int Id)
        //{
        //    var parentNode = _categoryService.GetById(Id);
        //    var nodes = _categoryService.GetAllCategorys().Select(_ => _.ParentId == parentNode.Id);
        //}
    }
}

WorkWithCSV.WebApp/Views/Home/Index.cshtml
@model WorkWithCSV.WebApp.Models.Home.HomeModel;
@{
    ViewData["Title"] = "Home Page";
}

<div class="row">
    <div class="col-md-12">
        <table>
            <tr>
                <td>Id</td>
                <td>Name</td>
                <td>ParentId</td>
            </tr>
            @foreach (var category in Model.Categories)
            {
                <tr>
                    <td>@category.Id</td>
                    <td>@category.Name</td>
                    <td>@category.ParentId</td>
                    <td>
                        @using (Html.BeginForm("Remove", "Home", new { id = category.Id }, FormMethod.Post, true, null))
                        {
                            @Html.ActionLink("Remove", "Remove", "Home", null, new { onclick = "onLinkClick(event)" })
                        }
                    </td>
                </tr>
            }
        </table>
    </div>
</div>

@section Scripts
    {
    <script>

        function onLinkClick(e) {
            e.preventDefault();
            e.stopPropagation();

            if (confirm("Are you really want to remove the category?")) {
                e.target.parentNode.submit();
            }

            return false;
        }

    </script>

}

WorkWithCSV.WebApp/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - WorkWithCSV.WebApp</title>

    <environment include="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
        <link rel="stylesheet" href="~/css/site.css" />
        <link type="text/css" href="~/css/StyleForTree.css" rel="stylesheet" />
    </environment>
    <environment exclude="Development">
        <link rel="stylesheet" href="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute" />
        <link rel="stylesheet" href="~/css/site.min.css" asp-append-version="true" />
    </environment>
</head>
<body>
    <nav class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a asp-area="" asp-controller="Home" asp-action="Index" class="navbar-brand">CSVGuide</a>
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li><a asp-area="" asp-controller="Home" asp-action="Index">Table</a></li>
                    <li><a asp-area="" asp-controller="Tree" asp-action="Index">Tree</a></li>
                </ul>
            </div>
        </div>
    </nav>

    <partial name="_CookieConsentPartial" />

    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; 2020 - WorkWithCSV.WebApp</p>
        </footer>
    </div>

    <environment include="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
        <script src="~/js/site.js" asp-append-version="true"></script>
    </environment>
    <environment exclude="Development">
        <script src="https://ajax.aspnetcdn.com/ajax/jquery/jquery-3.3.1.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha384-tsQFqpEReu7ZLhBV2VZlAu7zcOV+rXbYlF2cqB8txI/8aZajjp4Bqd+V6D5IgvKT">
        </script>
        <script src="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/bootstrap.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                crossorigin="anonymous"
                integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa">
        </script>
        <script src="~/js/site.min.js" asp-append-version="true"></script>
    </environment>

    @RenderSection("Scripts", required: false)
</body>
</html>

WorkWithCSV.WebApp/Views/Tree/Index.cshtml
@model WorkWithCSV.WebApp.Models.Tree.SeededCategories;

<ul class="tree" id="tree">

    @Html.Partial("_TreeCategories", Model)

</ul>


<script>
    // поместить все текстовые узлы в элемент <span>
    // он занимает только то место, которое необходимо для текста
    for (let li of tree.querySelectorAll('li')) {
        let span = document.createElement('span');
        li.prepend(span);
        span.append(span.nextSibling); // поместить текстовый узел внутрь элемента <span>
    }

    //  ловим клики на всём дереве
    tree.onclick = function (event) {

        if (event.target.tagName != 'SPAN') {
            return;
        }

        let childrenContainer = event.target.parentNode.querySelector('ul');
        if (!childrenContainer) return; // нет детей

        childrenContainer.hidden = !childrenContainer.hidden;
    }

    function onLinkClick(e) {
        e.preventDefault();
        e.stopPropagation();

        if (confirm("Are you really want to remove the category?")) {
            e.target.parentNode.submit();
        }

        return false;
    }
</script>

WorkWithCSV.WebApp/Views/Tree/_TreeCategories.cshtml
@model WorkWithCSV.WebApp.Models.Tree.SeededCategories;


@if (Model.Categories.Where(s => s.ParentId == Model.Seed).Any())
{
    <ul>
        @foreach (var node in Model.Categories)
        {
            if (node.ParentId == Model.Seed)
            {
                var inner = new WorkWithCSV.WebApp.Models.Tree.SeededCategories { Seed = node.Id, Categories = Model.Categories };


        <li>

            @node.Name

            @using (Html.BeginForm("Remove", "Tree", new { id = node.Id }, FormMethod.Post, true, null))
            {
                @Html.ActionLink("Edit", "Edit", "Tree", new { id = node.Id })
                <text> | </text>
                @Html.ActionLink("Delete", "Remove", "Tree", null, new { onclick = "onLinkClick(event)" })
            }

            @Html.Partial("_TreeCategories", inner)

        </li>
            }
        }
    </ul>
}